stateright/stateright

examples/paxos.rs
examples/wor.rs
src/actor/system.rs

Hi! Thanks so much for building this library, it's great!
As a first contribution, here's a change that lets users prune the portion of search space that consists of duplicate messages -- some systems have trivially idempotent messages, where exploring all the extra delivery schedules is just a waste of model-checking time.

Add duplicating_network flag.

---

Cargo.toml
src/actor/system.rs
src/checker.rs
src/test_util.rs

This PR adds a simple form of liveness-proerty checking -- "eventually" properties. They're implemented by assigning a bit-number to each such property and propagating a compact bitset (`IdSet` from the id-set crate) representing properties not-yet-established on a given path, along with the state, in the queue of states. Any property still not-yet-established when we arrive at a terminal state is marked as a counterexample discovery, as with "always" properties, and reported the same way.
These properties suffer from two possible false negatives:
- Cyclic paths are not disambiguated from DAG joins, so neither is considered terminal. If an eventually property is not met by the cycle-closing edge of a cyclic path, it is forgotten.
- DAG joins with different sets of liveness properties at …

Add support for "eventually" (at least acyclic liveness) properties.

---

src/actor.rs

Minor change but necessary for interop with the library I'm using stateright with and, I think, relatively harmless?

derive deault and deserialize for Id as well

---

examples/2pc.rs
src/actor.rs
src/actor/model.rs
src/actor/model_state.rs
src/actor/register.rs
src/actor/write_once_register.rs
src/checker/dfs.rs
src/checker/explorer.rs
src/checker/representative.rs
src/checker/rewrite.rs
src/checker/rewrite_plan.rs
src/semantics.rs
src/semantics/write_once_register.rs
src/util.rs
src/util/densenatmap.rs

This PR adds the required functionality to implement [VectorPaxos](https://github.com/cjen1/stateright/tree/vectorpaxos).
It makes several changes to the codebase:
- RewritePlan uses a closure
- Previously the rewrite plan only allowed for strict reindexing of types which implement `From<usize>`
- This changes it to carry some state which allows it to apply to more types, for example [ballots in VectorPaxos](https://github.com/Cjen1/stateright/blob/353312acd9808ce18365d6d119da7792bdfc3fa1/examples/vectorpaxos.rs#L28).
- Initialise timers to false
- Previously timers were initialised as an empty vec
- This meant that they could not be reindexed during the symmetry function.
- Add write-once-registers
- This PR also adds a write-once-register implementation
- This is the semantics provided …

Upstreaming changes for vectorpaxos

---

examples/linearizable-register.rs
examples/paxos.rs
examples/single-copy-register.rs

The `-i lo0` parameter referrers to the device/interface that tcpdump will listen on
and not all systems use `lo0` to refer to the loop back interface. Executing `tcpdump -D`
will display a list of devices available on the system and the user can find the current
loop back device:
For instance on my computer device 3, `lo`, is the loop back device:
$ tcpdump -D
1.wlp170s0 [Up, Running, Wireless, Associated]
2.any (Pseudo-device that captures on all interfaces) [Up, Running]
3.lo [Up, Running, Loopback]
4.bluetooth0 (Bluetooth adapter number 0) [Wireless, Association status unknown]
5.bluetooth-monitor (Bluetooth Linux Monitor) [Wireless]
6.nflog (Linux netfilter log (NFLOG) interface) [none]
7.nfqueue (Linux netfilter queue (NFQUEUE) interface) [none]
8.dbus-system (D-Bus system bus) …

Add a sentence in the spawn help for using 'tcpdump -D`

---

examples/2pc.rs
examples/increment.rs
examples/increment_lock.rs
examples/linearizable-register.rs
examples/paxos.rs
examples/single-copy-register.rs
src/checker.rs
src/lib.rs
src/report.rs

The report function currently only writes a predefined output to stdout, in some cases it may make sense to provide more information in the report or even send it somewhere else.
This PR adds a new `Reporter` trait that encapsulates what data can be reported from the checking process.
In order to ease the transition it also includes a `WriteReporter`, a reporter that can write to anything that implements `Write` using the old format.
One thing that I've in particular wanted to report on is the rate of states being processed for instance.

Allow custom reporting

---

src/checker/explorer.rs
ui/app.js
ui/index.htm

- Adds properties field per-state in the explorer API
- Renders property icons per-state (toggleable)
- Renders properties for currently selected state (toggleable)
- Renders breadcrumbs for states on a path to a discovery
Fixes #22

Dynamic property feedback

---

src/checker.rs
src/checker/explorer.rs
src/checker/on_demand.rs
ui/app.js
ui/index.htm

This checker waits for requests to check fingerprints before doing the checking. This makes exploring less resource-intensive, without the need to check every state to just explore a few paths.
There is a 'run to completion' button in the UI for letting the checker run without waiting, back to the normal functionality.
The checker itself is mostly a copy of the BFS checker, besides the modifications to wait for fingerprints.
A potential future change would be to merge this control-flow functionality into both the DFS and BFS checkers directly

Add an on-demand checker

---

src/checker.rs
src/checker/bfs.rs
src/checker/dfs.rs
src/checker/explorer.rs
src/checker/on_demand.rs
src/report.rs
ui/app.js
ui/index.htm

This introduces a new `CheckerBuilder::target_max_depth` function that enables users to limit the depth of the searches. This is implemented for the DFS and BFS checkers, but currently not the `on_demand` checker as that is not run eagerly anyway.
This also introduces a new report field `max_depth` that tracks the maximum depth explored. This is implemented for all checkers.
I'm happy for feedback on performance improvements / impacts of these and any improvements.
Fixes #36, Fixes #37

Add depth tracking and limiting

---

examples/linearizable-register.rs
examples/paxos.rs
examples/single-copy-register.rs
examples/timers.rs
src/actor.rs
src/actor/actor_test_util.rs
src/actor/model.rs
src/actor/model_state.rs
src/actor/ordered_reliable_link.rs
src/actor/register.rs
src/actor/spawn.rs
src/actor/timers.rs
src/actor/write_once_register.rs
src/checker/explorer.rs
src/checker/rewrite.rs
src/checker/rewrite_plan.rs

Adds a `Timer` type to the `Actor` trait.
This is used for triggering different behaviours on timeout, e.g. timeouts of different peers as well as timeouts for different functionality.
It changes the timers storage from `Vec<bool>` to a `Vec<Timers>` where `Timers` is effectively a hash set.
Fixes #41

Named timers

---

src/checker.rs
src/checker/bfs.rs
src/checker/dfs.rs
src/checker/on_demand.rs
src/report.rs

This introduces a new method on the checker trait for waiting for the completion of the checker (joining threads) as well as reporting. This reduces the artifact that done times can report after a delay from the actual finish.
I'm mainly wanting this for use in iterative DFS, its nice to start from a max depth of 1 but the first few depths lead to a group of sleeps which would be nice to avoid at least in the reported finish time.
I think further work would be interesting to effectively invert the reporting, sending report data events every time a checker pulls something off the job market or loops on its local set, that should bring the actual runtime down (no need to sleep).
Fixes #43

Report and join

---

src/actor/model.rs
src/actor/model_state.rs
src/actor/timers.rs
src/checker/explorer.rs

It is now possible for actors to crash.
If the model checker decides to crash an actor, it cancels all timers the actor has set, but it does not remove from the network any message addressed to it, so that in a future implementation it will be possible for the model checker to recover the actor and deliver such messages to it. (This would correspond to an actor recovering "soon enough").
The user can specify the maximum number of actors that can be contemporarily crashed. For example, the Raft consensus algorithm can tolerate _f_ contemporarily crashed servers with 2 _f_ + 1 servers.

Implement crash failures

---

src/test_util.rs

Let `with_path` and `check` take the ownership of `self to avoid cloning
Closes #55

Avoid cloning in `DGraph`

---

examples/paxos.rs
src/actor.rs
src/actor/model.rs
src/actor/ordered_reliable_link.rs
src/actor/register.rs
src/actor/write_once_register.rs
ui/app.css

This enables showing a useful name in the explorer next to the id, e.g. differentiating servers and clients more clearly.
I'd be happy with updating the `name` function's args if needed.

Add name function to actor trait

---

src/checker/bfs.rs
src/checker/dfs.rs
src/checker/on_demand.rs
src/job_market.rs
src/lib.rs

This extracts the `JobMarket` struct from the different checkers and provides a uniform API.
This ends up making the checkers a bit cleaner, and gets us some nicer behaviour in the job market.
Primarily this was needed in order to track when a thread has panicked. When one does:
1. the `drop` implementation is called for the `JobMarket`
2. This closes the market
3. More interactions with the `JobMarket` on other threads will eventually close the threads.
Closes #29 
Different design than described in #29 but I think it makes more sense to view the panic as a bug in the model code rather than a property violation and just stop the checking there.

Refactor JobMarket and handle checker threads panicking

---

examples/paxos.rs
src/checker.rs
src/checker/bfs.rs
src/checker/dfs.rs
src/checker/on_demand.rs
src/checker/simulation.rs
src/job_market.rs

Fixes #69
- DFS and BFS checkers use the shared job market, so they rely on the timeout now implemented within that.
- Simulation checker does not use the job market, so relies on its own logic for timeout.
This has the benefit of doing a 'clean' shutdown for each checker type, clearing work to be done, rather than stopping them mid-flow.
This might be updated when the checkers get unified with DPOR #7

Add checker timeout

---

src/actor.rs
src/actor/model.rs
src/actor/network.rs

Fixes #73 by remembering the last envelop delivered in the network. 
In this way, the actor model can differentiate two actions taken next that does not change the actor state, so that the Web UI of explorer can work as expected by the user.

fix: non-unique fingerprint in unordered duplicating network

---

examples/interaction.rs
examples/linearizable-register.rs
examples/lww-register.rs
examples/paxos.rs
examples/single-copy-register.rs
examples/timers.rs
src/actor.rs
src/actor/actor_test_util.rs
src/actor/model.rs
src/actor/model_state.rs
src/actor/ordered_reliable_link.rs
src/actor/register.rs
src/actor/spawn.rs
src/actor/write_once_register.rs
src/checker/explorer.rs

(As discussed on https://github.com/stateright/stateright/discussions/79)
The `actor::Out::choose_random` method gives a way to model
non-deterministic choices by an Actor. It supplies a vec of choices with
type `Actor::Random`, which `ActorModelState` will then pick one. A string
key is also provided with the choose_random method, which can be used
to overwrite or remove previously registered random choices.
For explorer and DFS / BFS simulations, these random choices are modeled
as part of `ActorModel::actions`. For `actor::spawn`, the random choice is
is modeled as a timer with a duration between 0 - 10 seconds.
Because of the additions of the generic associated type Random and the
type parameters, this is a major semver change. Existing users of the
actor framework will need to add …

Add `Actor::on_random` to model non-determinism

---

examples/increment.rs
examples/paxos.rs
src/actor/model.rs
src/actor/model_state.rs
src/actor/register.rs
src/actor/write_once_register.rs
src/checker.rs
src/checker/bfs.rs
src/checker/dfs.rs
src/checker/on_demand.rs
src/checker/simulation.rs
src/job_market.rs
src/lib.rs
src/util/vector_clock.rs

I made some modifications:
Fixed some typos in code comments.
And in `model_state.rs`:
1. Modified the `serialize` function.
2. Based on the same logic, also modified the `fmt` function.
3. In the `Hash` and `Eq` implementations, I noticed that both were missing handling for the `crashed` and `random_choices` fields. Based on my understanding, both of these fields should be considered when comparing `ActorModelState` instances for equality. So I added handling for them. Additionally, in order to use the `hash` and `eq` methods for the `random_choices` field, I derived `Hash`, `Eq`, and `PartialEq` for the `RandomChoices` struct.
Also, in `visits_expected_states` in `model.rs`, I change the initialization of `random_choices` to pass the test after the 3rd change above.

Fix bugs in `model_state.rs`

---

src/job_market.rs

We don't actually need the loop and can just sleep the duration directly.

Fix timeout thread to sleep directly

---

src/actor/model.rs
src/checker.rs
src/checker/bfs.rs
src/checker/dfs.rs
src/checker/on_demand.rs
src/checker/simulation.rs
src/test_util.rs

Assuming that an eventually counter-example is found, then the next terminal state where there are still discoveries to find, will have the ebits set and hence not early exist and thus overwrite the eventually counterexample.
This PR stops the above behaviour.
There is one commit which adds the test, and one commit with the corresponding fix for all checkers.
There are also other tests which seem to be failing, but that is the same as on the main branch.

Eventually fix
